In [23]:
print("hello")

hello

In [24]:
import pandas as pd

In [25]:
pd.DataFrame([1,2,3],columns=['A'],index=['A','B','C'])

   A
A  1
B  2
C  3

In [26]:
pd.DataFrame((1,2,3))

   0
0  1
1  2
2  3

In [27]:
pd.DataFrame({"Months":["jan","Feb"],"Sales":[20,40]})

  Months  Sales
0    jan     20
1    Feb     40

In [28]:
import numpy as np
np.random.seed(11)
df=pd.DataFrame(np.random.randint(0,10,(3,3)))

In [29]:
df

   0  1  2
0  9  0  1
1  7  1  7
2  2  8  0

In [30]:
"A B C".split()

['A', 'B', 'C']

In [31]:
np.random.seed(121)
df=pd.DataFrame(np.random.randint(0,10,(3,3)),columns="A B C".split(),index='P Q R'.split())
df

   A  B  C
P  2  5  8
Q  4  1  4
R  3  0  2

In [32]:
df

   A  B  C
P  2  5  8
Q  4  1  4
R  3  0  2

In [33]:
import pandas as pd
df = pd.read_csv("C:/Users/hchin/Downloads/Superstore sales dataset.csv")

In [34]:
df.shape

(9994, 21)

In [35]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [36]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [37]:
df.tail(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.0,13.320
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

In [38]:
df.index

RangeIndex(start=0, stop=9994, step=1)

In [39]:
df[['Row ID','Order ID','Sales']].head(2)

   Row ID        Order ID   Sales
0       1  CA-2016-152156  261.96
1       2  CA-2016-152156  731.94

In [41]:
df.iloc[2:8,1:3]

         Order ID  Order Date
2  CA-2016-138688   12/6/2016
3  US-2015-108966  11/10/2015
4  US-2015-108966  11/10/2015
5  CA-2014-115812    9/6/2014
6  CA-2014-115812    9/6/2014
7  CA-2014-115812    9/6/2014

In [42]:
df.iloc[2:8,[2,5,7]]

   Order Date Customer ID    Segment
2   12/6/2016    DV-13045  Corporate
3  11/10/2015    SO-20335   Consumer
4  11/10/2015    SO-20335   Consumer
5    9/6/2014    BH-11710   Consumer
6    9/6/2014    BH-11710   Consumer
7    9/6/2014    BH-11710   Consumer

In [43]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [44]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [45]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [46]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [47]:
np.finfo(np.float16).min

np.float16(-6.55e+04)

In [48]:
df.select_dtypes(include=['int64','float64']).head(2)

   Row ID  Postal Code   Sales  Quantity  Discount    Profit
0       1        42420  261.96         2       0.0   41.9136
1       2        42420  731.94         3       0.0  219.5820

In [49]:
df.select_dtypes(include=['str']).head(2)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
0,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase
1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,..."

In [50]:
df.select_dtypes(include=['str']).shape

(9994, 15)

In [51]:
df.select_dtypes(include=['int64','float64']).shape

(9994, 6)

In [52]:
subset_df=df.iloc[0:5,0:5].copy()

In [53]:
subset_df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode'], dtype='str')

In [54]:
subset_df[['Row ID','Order ID','Ship Mode','Ship Date']].min()

Row ID                    1
Order ID     CA-2016-138688
Ship Mode      Second Class
Ship Date        11/11/2016
dtype: object

In [55]:
df[['Sales']].mean()

Sales    229.858001
dtype: float64

In [56]:
df['Ship Mode'].str.upper().head(2)

0    SECOND CLASS
1    SECOND CLASS
Name: Ship Mode, dtype: str

In [57]:
df['Ship Mode'].str.lower().head(2)

0    second class
1    second class
Name: Ship Mode, dtype: str

In [58]:
df['Ship Mode'].str.capitalize().head(2)

0    Second class
1    Second class
Name: Ship Mode, dtype: str

In [59]:
df['Region'].str.capitalize().head(2)

0    South
1    South
Name: Region, dtype: str

In [60]:
df['Ship Mode'].str.title().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: str

In [61]:
df['Ship Mode'].str.len().head(2)

0    12
1    12
Name: Ship Mode, dtype: int64

In [62]:
df['Ship Mode'].str.capitalize().tail(2)

9992    Standard class
9993      Second class
Name: Ship Mode, dtype: str

In [63]:
df['Ship Mode'].str.strip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: str

In [64]:
df['Ship Mode'].str.lstrip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: str

In [65]:
df['Ship Mode'].str.rstrip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: str

In [66]:
df['Ship Mode'].str.split(" ").str[0]

0         Second
1         Second
2         Second
3       Standard
4       Standard
          ...
9989      Second
9990    Standard
9991    Standard
9992    Standard
9993      Second
Name: Ship Mode, Length: 9994, dtype: object

In [67]:
df['Ship Mode'].str.split(" ").str[1]

0       Class
1       Class
2       Class
3       Class
4       Class
        ...
9989    Class
9990    Class
9991    Class
9992    Class
9993    Class
Name: Ship Mode, Length: 9994, dtype: object

In [68]:
df['Ship Mode'].str.count("Second")

0       1
1       1
2       1
3       0
4       0
       ..
9989    1
9990    0
9991    0
9992    0
9993    1
Name: Ship Mode, Length: 9994, dtype: int64

In [69]:
df['Region'].str.count("South")

0       1
1       1
2       0
3       1
4       1
       ..
9989    1
9990    0
9991    0
9992    0
9993    0
Name: Region, Length: 9994, dtype: int64

In [70]:
df['Ship Mode'].str.pad(width=20,side='left',fillchar="+")

0       ++++++++Second Class
1       ++++++++Second Class
2       ++++++++Second Class
3       ++++++Standard Class
4       ++++++Standard Class
                ...
9989    ++++++++Second Class
9990    ++++++Standard Class
9991    ++++++Standard Class
9992    ++++++Standard Class
9993    ++++++++Second Class
Name: Ship Mode, Length: 9994, dtype: str